style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
<<<<<<< HEAD
  repository_url: https://github.com/Thoshi-o/prac-git-tag
=======
  repository_url: Y
>>>>>>> master
options:
  commits:
    # filters:
    #   Type:
    #     - feat
    #     - fix
    #     - perf
    #     - refactor
  commit_groups:
    # title_maps:
    #   feat: Features
    #   fix: Bug Fixes
    #   perf: Performance Improvements
    #   refactor: Code Refactoring
  header:
<<<<<<< HEAD
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
=======
    pattern: "^((\\w+)\\s.*)$"
    pattern_maps:
      - Subject
      - Type
>>>>>>> master
  notes:
    keywords:
      - BREAKING CHANGE